variables:
  SERVICE_SLUG: "joss-common-services"
  DOCKER_HOSTNAME: "gitlab-docker.mtest.no"

include:
  - project: development/cicd/gitlab-templates
    ref: main
    file: Misc/Rules.yml
  - project: development/backend/cicd-pipelines
    ref: main
    file:
      ###--------SETUP-----------###
      - CI/Common.Variables.yml
      - CI/Common.Pipeline.Setup.yml
      ###--------STAGES----------###
      - CI/Stage/Setup.yml
      - CI/Stage/Testing/Build.MkDocs.yml
      - CI/Stage/Testing/Compile.yml
      - CI/Stage/Testing/UnitTest.yml
      - CI/Stage/Testing/TestSummary.yml
      - CI/Stage/Testing/Scan.Sonarqube.yml
      - CI/Stage/Upload.Metrics.yml
      - CI/Stage/Release.yml
      - CI/Stage/Post.Release.Maven.Artifactory.yml

stages: # List of stages for jobs, and their order of execution
  - setup
  - compile
  - unit-test
  - testing
  - scanning
  - release
  - post-release

# Job to trigger a build and sync to Maven. Actual execution will be done on osl-gitsync1.!reference:
# TODO: Set up dedicated runner instead of osl-gitsync1, and control build in this pipeline spec
trigger-maven-central-sync:
  stage: post-release
  allow_failure: true
  tags:
    - development
  rules:
    # do not run in forked repos
    - if: $CI_PROJECT_UPSTREAM_BOOL != "true"
      when: never
    # only run on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    # protect the keyfile
    - chmod 600 ${GITSYNC_KEY}
  script:
    - ssh -T -o StrictHostKeychecking=no -o IdentitiesOnly=yes -i ${GITSYNC_KEY} gitsync@osl-gitsync1 mvnsync https://git:${GITSYNC_TOKEN}@gitlab.mnemonic.no/development/backend/joss/common-services.git ${NO_SNAPSHOT_VERSION}

# Job to trigger a sync to GitHub. Actual execution will be done on osl-gitsync1.!reference:
# TODO: Set up dedicated runner instead of osl-gitsync1, and control build in this pipeline spec
trigger-github-sync:
  stage: post-release
  allow_failure: true
  tags:
    - development
  rules:
    # do not run in forked repos
    - if: $CI_PROJECT_UPSTREAM_BOOL != "true"
      when: never
    # only run on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    # protect the keyfile
    - chmod 600 ${GITSYNC_KEY}
  script:
    - ssh -T -o StrictHostKeychecking=no -o IdentitiesOnly=yes -i ${GITSYNC_KEY} gitsync@osl-gitsync1 gitsync https://git:${GITSYNC_TOKEN}@gitlab.mnemonic.no/development/backend/joss/common-services.git https://github.com/mnemonic-no/common-services.git
